name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # run every 10 a.m., which is UTC 2 a.m + 8
    - cron:  '0 7 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: run
        run:  python3 auto_badmintion/BadmintonCrawler.py
